# Generated by Django 6.0.6 on 2026-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('technology', 'Technology'), ('business', 'Business'), ('entertainment', 'Entertainment')], default='technology', max_length=50),
        ),
    ]
